version: '3.8'

services:
  hw6:
    build: ./
    entrypoint: ./hw6
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - dbMySQL
      - dbMongo
  dbMySQL:
    image: mysql:latest
    volumes:
      - ./schema/DB_up.sql:/docker-entrypoint-initdb.d/DB_up.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: webDB
    ports:
      - "3307:3306"
  dbMongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: webDB
    restart: always
    ports:
      - '27017:27017'
